## 3번째 스터디 이후 정리
----------------

<br />

### `형변환`과 관련하여 ...
- as 연산자는 참조형에만 사용이 가능하고 기본 값형식에는 사용이 불가능하다. 
- 기본 값 형식에는 `int`, `string`, `byte`, `char`, `long` ...
- 기본 값 형식에 `nullable` => `?` 키워드는 선언문에 들어가는 키워드이기에 사용가능
- int => value 타입 
- INTEGER => reference 타입

<br />

### 예외처리를 하는 근본적인 이유
- 프로그램의 안전성 및 신뢰성을 확보하기 위한 이유 
- 예외처리를 하지 않은 코드는 예외발생시 오류로 프로그램이 죽게됨 => `운영체제(OS)` 단에서 확인해볼 수 있음 => 이벤트 뷰어를 통해보면 에러로 프로그램이 종료됨
- 하지만 예외처리를 해주게 되면 `catch`문에 의해서 예외를 잡아서 처리하기 때문에 적어도 오류 발생 후 죽지는 않음

<br />

### `Exception e` 사용하지 말기
- 발생하지 않는 에러때문에 프로그램의 성능이 떨어짐 => 과한 투자
- 안타는 코드가 생김.
- 모든 에러를 다잡아서 어디서 생긴 문제인지 파악이 안됨

<br />

### `throw new Exception(...);`은 가능한 사용하지 않기
- `Exception` 객체이기 때문에 크기도 크면서 이후에 배포시에는 코드에 포함하지 않도록 하기도함. 
- 간혹 `stack trace`를 확인해보고 싶다면 `new Exception` 인스턴스 생성부는 제외하고 `throw`문만 사용해서 예외를 던지기도함 => 이 경우는 예외처리가 안되는 경우의 최후 방법 
  - 해당 방법을 사용시에도 문제점이 있는데 이는 어떤 타입의 예외인지가 체크가 안되고 이에 의해 끝까지 타고올라가 해당 예외와 관련된 `stack trace`를 확인할 수 있는것임 

=> 애초에 권장되지 않는 방법임 - 최대한 개발과정에서 발생가능한 예외를 생각하고 구성하는 것을 추천함.

<br />

### `when` 키워드 
- 예외처리 중 특정한 값을 처리하거나 확인하고 싶을때 사용. 

<br />

### `try-catch` 문 
- 치명적인 에러가 발생할 수 있는 경우에만 사용 .
- 너무 남발하거나 한번에 많은 코드를 `try-catch`문으로 묶게되면 프로그램의 성능이 안좋아진다.

<br />

### `reflection` 으로 프로퍼티 내부동작 확인해보기 => 여쭤보기! 

<br />
-------------------
## 다음 발표에 포함할 내용

<br />

### `catch` 문에서 `return`을 하게되면 `finally`문을 실행하는지?
```csharp
class Program
{
    static int divideMethod(int a, int b)
    {
        try
        {
            return a / b;
        }
        catch (DivideByZeroException e)
        {
            Console.WriteLine("나누기 예외 발생");
            throw e;
        }
    }
    static void Main(string[] args)
    {
        try
        {
            Console.WriteLine("a/b 수식에서 a 의 값을 입력하세요 : ");
            string aa = Console.ReadLine();
            int a = Convert.ToInt32(aa);

            Console.WriteLine("a/b 수식에서 b 의 값을 입력하세요 : ");
            string bb = Console.ReadLine();
            int b = Convert.ToInt32(bb);

            Console.WriteLine($"{a}/{b} = {divideMethod(a, b)}");

            Console.WriteLine("프로그램 종료");
        }
        catch (DivideByZeroException e)
        {
            Console.WriteLine($"에러 : {e.Message}");
            return;
        }
        finally
        {
            Console.WriteLine("프로그램 종료");
        }
    }
}
```
```java
Output

a/b 수식에서 a 의 값을 입력하세요 :
5
a/b 수식에서 b 의 값을 입력하세요 :
0
나누기 예외 발생
에러 : Attempted to divide by zero.
프로그램 종료
```
- catch문에서 `return`을 통해 메소드를 종료하더라도 `finally` 문은 실행함

<br />

### `catch`문이 여러개일 때 어떤 순서로 타는지 조사.

```csharp
class Program
{
    class A
    {
        public int field;
        public static int getField(A obj)
        {
            return obj.field;
        }
    }
    
    static void Main(string[] args)
    {
        try
        {
            // DivideByZeroException
            int a = 10;
            int b = 0;
            Console.WriteLine(a / b);

            // NullReferenceException
            A obj = null;
            Console.WriteLine(A.getField(obj));

            // IndexOutOfRangeException            
            int[] arr = { 1, 2, 3 };
            for (int i = 0; i < 4; i++)
            {
                Console.WriteLine(arr[i]);
            }
        }
        catch (DivideByZeroException e)
        {
            Console.WriteLine("에러 : {0}", e.Message);
        }
        catch(NullReferenceException e)
        {
            Console.WriteLine("에러 : {0}", e.Message);
        }
        catch (IndexOutOfRangeException e)
        {
            Console.WriteLine("에러 : {0}", e.Message);
        }
        catch (Exception e)
        {
            Console.WriteLine("에러 : {0}", e.Message);
        }
        finally
        {
            Console.WriteLine("프로그램 종료");
        }
    }
}
```
```java
Output

ⅰ) 에러 : Attempted to divide by zero.

ⅱ) 에러 : Object reference not set to an instance of an object.

ⅲ) 에러 : Index was outside the bounds of the array.

```

- `catch` 문은 기본적으로 예외가 발생하면 `try` 블록과 가장 가까운 `catch`블록부터 순서대로 검사한다.
- 다중 `catch`문을 사용시 `Exception` 클래스의 계층관계에 주의해야한다.
- 예외에서 가장 상위에 있는 클래스는 `Exception` 클래스이기에 가장 아래쪽에 정의해야함
- `Exception` 클래스와 같이 상위에 있는 클래스를 가장 위에 정의하면 모든 예외를 처리하므로 다음 `catch`문부터는 비교 수행을 할 수 없다.
- 따라서 Exception 클래스의 계층관계에 따른 `catch`블록 순서에 유의해야한다.

<br />

### ⭐️⭐️⭐️ 예외 throw 및 예외 처리 관련 성능 고려 사항 ⭐️⭐️⭐️ㄴ
 
- 예외 throw 또는 처리는 상당한 양의 시스템 리소스와 실행 시간을 소비함. 
- 예측 가능한 이벤트 또는 흐름 제어를 처리 하는 것이 아니라 진정한 비정상적인 조건을 처리 하는 경우에만 예외를 throw 함. 
- 예를 들어, 클래스 라이브러리를 개발 하는 경우와 같이 메서드 인수가 잘못 된 경우 예외를 throw 하는 것이 적절 `잘못 된 메서드 인수입니다.` 사용 오류의 결과가 아닌 경우 특별 한 문제가 발생 했음을 의미함.
-  반대로 사용자 입력이 잘못 된 경우 예외를 throw 하지 말 것. 사용자가 가끔 잘못된 데이터를 입력 해야 할 수 있기 때문. 대신 사용자가 유효한 입력을 입력할 수 있도록 재시도 메커니즘을 제공. 또는 예외를 사용하여 사용 오류를 처리 하지 말 것. 대신 `Assertion`을 사용하여 사용 오류를 식별하고 수정.

또한 반환 코드에 충분 한 경우 예외를 throw 하지 않습니다. 반환 코드를 예외로 변환 하지 않습니다. 그리고 예외를 정기적으로 catch 하지 않고 무시 한 다음 처리를 계속 합니다.