## System.Exception클래스, throw문
----------------------------------------------------------------

<br />

- System.Exception 클래스는 모든 Exception의 Base클래스이다. 
    - 모든 Exception들은 System.Exception 클래스를 상속받는다.
    - 앞서 사용했던 IndexOutOfRangeException 예외 클래스도 System.Exception으로부터 파생된 것

<br />

- System.Exception을 이용해서 모든 예외사항을 처리하지 않는 이유 
  - 개발자가 예상하지 못했던 예외를 처리할 수는 있지만, 처리하지 않아도 될 예외까지 모두 처리를 함으로써 오류가 발생할 수 있기 때문에 System.Exception을 사용하는 것은 신중하게 고려해야한다.

<br />

#### throw문 형식
```csharp
    try
    {
       throw new Exception("예외를 던짐");
    }
    catch(Exception e)
    {
        Console.WriteLine(e.Message);
    }
```

<br />

#### 사용 코드 예제

```csharp
using System.Collections;

namespace ExceptionEx
{
    
    class Program
    {
        static void throwMethod(int aa)
        {
            if (aa < 5 ) { Console.WriteLine($"{aa}"); }
            else { throw new Exception("aa는 5보다 크다."); }
        }
        static void Main(string[] args)
        {
            try 
            { 
            throwMethod(1);
            throwMethod(2);
            throwMethod(3);
            throwMethod(4);
            throwMethod(5); // => catch 문으로 넘어간
            throwMethod(6); // 6은 수행되지 않음. 
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }

            Console.WriteLine("종료");
        }
    }
}
```
```java
Output

1
2
3
4
aa는 5보다 크다.
종료
```
<br />

- try문 내에서 예외가 발생하면 try문 내 코드를 모두 실행하지 않고 catch문으로 예외를 던지며 넘어간다.
- 이후 catch문 내 코드를 실행한 뒤 catch문을 벗어나 다른 코드를 실행하고 프로그램을 정상 종료한다.
- 즉, try문 내에서 예외가 발생하면 해당 try문 내에서의 동작은 중지하지만 프로그램의 전체적인 동작은 정상적으로 동작한다.